# Generated by Django 5.0.6 on 2024-08-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(default='Software Engineer', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=30),
        ),
    ]
