# Generated by Django 5.0.6 on 2024-08-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profession_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
