# Generated by Django 5.0.6 on 2024-09-23 14:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(default='dummyimage.jpg', max_length=255, verbose_name='image'),
        ),
    ]
