# Generated by Django 5.0.6 on 2024-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
