# Generated by Django 5.0.6 on 2024-08-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
