# Generated by Django 5.0.6 on 2024-08-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
