# Generated by Django 5.0.6 on 2024-08-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creator',
            name='service_areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
