# Generated by Django 5.0.6 on 2024-08-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_creator_experience_years_creator_service_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
