# Generated by Django 5.0.6 on 2024-08-24 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_creator_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.creator'),
        ),
    ]
