# Generated by Django 5.0.6 on 2024-08-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_creatorrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='message',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='status',
        ),
    ]
