# Generated by Django 5.0.6 on 2024-08-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_alter_creatorrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
