# Generated by Django 5.0.6 on 2024-09-01 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_alter_campaigns_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaigns'),
            preserve_default=False,
        ),
    ]
