# Generated by Django 5.0.6 on 2024-09-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_review_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('cancel', 'Canceled'), ('completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
