# Generated by Django 5.0.6 on 2024-09-23 14:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_alter_campaigns_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder_image_public_id', max_length=255, verbose_name='image'),
        ),
    ]
